# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b54bdebf9e953e46b8403df80249ce3ac6fb8949f6f4425651e85d0924bd8ba70d2eb30f0a7189310a6d1ada49ee1322d7f12f10bbd35e99c358adf16d0650e2

test:
  secret_key_base: e0d21e91b854d481c6ef351f0e3c4121d7713e8b20c62d25e4d16bcc0dee4cd4203821b037b50cdc3e4d60f73e33beda81b15e38dac419abc49d778464f5d152

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
